### ISSUE TITLE
Datafile with multiple spectral windows 

### ISSUE THREAD

**Issue by hrkloeck** [ska-sa/dask-ms#158]
*I'm not sure where to place this, since its not really an issue its a question:
I have a file with 3 spectral windows each of it consists of 67 channels, but it sees that I can read only 1 spw.

This is how I loaded the data
ms       = xds_from_ms(MSFN,chunks={'row':1000},group_cols=['FIELD_ID'],table_keywords=False,column_keywords=False) [0] 

So this provides me with a data from e.g. source 1

a = 10
b = 20

sel_bsl    = da.logical_and(ms.ANTENNA1.data == a, ms.ANTENNA2.data == b)    
bsl_data   = dask.compute(ms.DATA.data[sel_bsl])

print(len(bsl_data[0]))   # this is consistent with the length of the 
time_cent  = dask.compute(ms.TIME_CENTROID.data[sel_bsl])
print(len(time_cent[0]))

print(len(bsl_data[0][0])) 

This has a length of 67, but I would actually expect something else..

Could you please advice me, maybe I made a mistake in the grouping?

**Comment by hrkloeck** [comment]
Many Measurement Sets columns are defined as variably shaped, but the actual data is fixed. dask-ms will infer the shape of the data from the first row and must be consistent with that of other rows. For example, this may be issue where multiple Spectral Windows are present in the Measurement Set with differing channels per SPW.

dask-ms works around this by partitioning the Measurement Set into multiple datasets. The first row's shape is used to infer the shape of the partition. Thus, in the case of multiple Spectral Window's, we can partition the Measurement Set by DATA_DESC_ID to create a dataset for each Spectral Window.

**Comment by sjperkins** [comment]
Apologies for not responding to this sooner (it was a long weekend in ZA), but I'm glad you figured the solution out!
