### ISSUE TITLE
Example code uses old syntax for the scheduler.

### ISSUE THREAD

**Issue by tmolteno** [ska-sa/dask-ms#71]
In the examples directory, the code for the scheduler_context uses the old version of the syntax for setting the scheduler.

Old Syntax:
`    dask.set_options(get=dask.threads.get)`
New Syntax:
`    dask.config.set(scheduler='threads')`

**Comment by sjperkins** [comment]
Thanks for the report @tmolteno. I should probably add some test cases that ensure that the examples run through.

**Comment by sjperkins** [comment]
Closed by #78
